<a href="https://colab.research.google.com/github/maria2021831011/machine_learning/blob/main/2_7_complete_numpy_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#numpy numerical python
#advtg in
#allows several mathematical operations
#faster operation

In [2]:
import numpy as np

#list vs numpy_time taken


In [4]:
from time import process_time

#list time

In [6]:
python_list=[i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.0017742089999996935


In [8]:
numpy_array=np.array([i for i in range(10000)])
start_time=process_time()
numpy_array+=5
end_time=process_time()
print(end_time-start_time)

0.0013900260000001552


#numpy arrays

In [9]:
a=np.array([1,2,3,4,5])
print(a)
print(a.shape)
print(type(a))

[1 2 3 4 5]
(5,)
<class 'numpy.ndarray'>


#2d & type

In [10]:
b=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(b)
print(b.shape)


[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
(2, 4)


#initial  placeholder in numpy arrays

In [12]:
c=np.zeros((4,5))
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
#initialize one
d=np.ones((3,3),dtype=int)
print(d)


[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [16]:
#initialize particular value
a=np.full((5,4),5)
print(a)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [18]:
#initialize identity matrix
b=np.eye(5)
print(b)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [20]:
#initialize random value
e=np.random.random((3,4))
print(e)

[[0.58199403 0.54129121 0.05564562 0.47654673]
 [0.30930298 0.32042682 0.86986666 0.21781559]
 [0.69227497 0.90930498 0.0834481  0.65913031]]


In [22]:
#random specific values arrays within range
a=np.random.randint(10,100,(3,5))
print(a)

[[39 75 96 24 30]
 [57 28 95 58 87]
 [72 66 79 56 90]]


In [24]:
#evenly spaced line
a=np.linspace(10,30,6)
print(a)

[10. 14. 18. 22. 26. 30.]


In [26]:
#evenly specifying step
a=np.arange(10,30,5)
print(a)

[10 15 20 25]


#list convert to numpy array

In [27]:
l=[10,20,30,40,50]
print(l)
print(type(l))
a=np.asarray(l)
print(a)
print(type(a))

[10, 20, 30, 40, 50]
<class 'list'>
[10 20 30 40 50]
<class 'numpy.ndarray'>


#analyzing numpy

In [28]:
a=np.random.randint(10,90,(5,5))
print(a)
#rows col
print(a.shape)
#dimention
print(a.ndim)
#elements
print(a.size)
#elements type
print(a.dtype)

[[40 16 11 24 83]
 [52 35 79 81 75]
 [27 53 78 52 37]
 [32 26 23 51 18]
 [15 41 66 82 71]]
(5, 5)
2
25
int64


#mathematical operation

In [29]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[9 4 7]
 [1 6 4]
 [3 4 4]]
[[11 18 15]
 [15 14 15]
 [15 13 18]]
[[20 22 22]
 [16 20 19]
 [18 17 22]]
[[ -2 -14  -8]
 [-14  -8 -11]
 [-12  -9 -14]]
[[ 99  72 105]
 [ 15  84  60]
 [ 45  52  72]]
[[0.81818182 0.22222222 0.46666667]
 [0.06666667 0.42857143 0.26666667]
 [0.2        0.30769231 0.22222222]]


#array transformation

In [31]:
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)
TRA=a.transpose()
print(TRA)
print(TRA.shape)

[[5 8 9]
 [9 9 5]]
(2, 3)
[[5 9]
 [8 9]
 [9 5]]
(3, 2)


In [32]:
#RESIZE
a=np.random.randint(0,10,(2,3))
print(a)
a.resize(3,2)
print(a)

[[3 4 5]
 [4 2 3]]
[[3 4]
 [5 4]
 [2 3]]
