<a href="https://colab.research.google.com/github/maria2021831011/machine_learning/blob/main/5_4_matrix_operation_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:

# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [3]:
print(A)

[[2 3]
 [4 5]]


In [4]:
print(B)


[[6 7]
 [8 9]]


In [5]:
A.shape

(2, 2)

In [6]:
B.shape

(2, 2)

In [7]:
sum=A+B
print(sum)


[[ 8 10]
 [12 14]]


In [8]:

# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [11]:
print(matrix_1)

[[2 6 9]
 [5 8 5]
 [8 5 1]]


In [12]:
print(matrix_2)

[[2 9 7]
 [9 7 5]
 [8 2 7]]


In [9]:
sum = np.add(matrix_1, matrix_2)

In [10]:


print(sum)

[[ 4 15 16]
 [14 15 10]
 [16  7  8]]


In [13]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [14]:
difference = A - B

In [15]:

print(difference)

[[-4 -4]
 [-4 -4]]


In [16]:

# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))
diff = np.subtract(matrix_1, matrix_2)


print(diff)

[[  4  -9   2]
 [  5  -1  -6]
 [  4  -8 -16]]


In [17]:


x = 5
y = np.random.randint(10, size=(4,4))

product = np.multiply(x,y)


print(product)

[[45 10 45 30]
 [30 35  0 40]
 [10 20 30  0]
 [25 30 45 20]]


In [18]:

# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [19]:

product = np.dot(matrix_3, matrix_4)

In [20]:


print(product)

[[ 3 12 15  3]
 [ 9 15 10  8]
 [17 19  8  8]]


In [21]:

product.shape

(3, 4)