<a href="https://colab.research.google.com/github/maria2021831011/machine_learning/blob/main/working_with_matrics_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
matrix=np.array([[1,2],[3,4],[5,6]])

In [3]:
matrix.shape

(3, 2)

In [4]:
mat=np.random.rand(2,2)

In [5]:
print(mat)

[[0.36160576 0.97524829]
 [0.45457438 0.76516562]]


transpose matrix

In [8]:
matt=np.random.randint(100,size=(2,4))

In [9]:
print(matt)

[[54 80 99 89]
 [84 42 84 83]]


In [11]:
trans=np.transpose(matt)

In [12]:
print(trans)

[[54 84]
 [80 42]
 [99 84]
 [89 83]]


In [13]:
identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:

null_matrix = np.zeros((7,7))
print(null_matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [15]:
matrix_3 = np.ones((10,10), dtype=int)
print(matrix_3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
